<a href="https://colab.research.google.com/github/dlsanf2000/new/blob/master/top_n_%EC%BB%B4%ED%93%A8%ED%84%B0%EC%A0%95%EB%B3%B4%ED%95%99%ED%9A%8C_%EB%85%BC%EB%AC%B8_%EA%B2%B0%EA%B3%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
!pip install -U -q PyDrive 
from pydrive.auth import GoogleAuth 
from pydrive.drive import GoogleDrive 
from google.colab import auth
from oauth2client.client import GoogleCredentials
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
df_raw = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/real data.xlsx', header = 2)
df_raw.head()
df_raw = df_raw.drop([0,1])
df1 = df_raw[['Age', 'Sex', 'ASA', 'BMI', 'DM_history', 'Pulmonary_disease',
        'Liver_disease', 'Kidney_disease', 'Smoking_history',
        'Prior_Dx_cancer','pT','pM', 'pTNM', 'K-ras', 'N-ras', 'BRAF', 'LVI', 'PNI', 'pN', 'Harvested_LN','Positive_LN','Postop_Chemo_Regimen']]
df = df1.copy()


In [ ]:
# df = df.dropna()

df.isna().sum()

Age                        0
Sex                        0
ASA                        0
BMI                        0
DM_history                 0
Pulmonary_disease          0
Liver_disease              0
Kidney_disease             0
Smoking_history            0
Prior_Dx_cancer            0
pT                         8
pM                         6
pTNM                       8
K-ras                      0
N-ras                      0
BRAF                       0
LVI                       48
PNI                       46
pN                         4
Harvested_LN              59
Positive_LN               56
Postop_Chemo_Regimen    1385
dtype: int64

In [ ]:
print(df['LVI'].value_counts())
df['LVI']=df['LVI'].fillna(32)
df['LVI'].isna().sum()

32    1763
31    1121
11     282
4       51
12      20
21      19
42      10
41       5
22       1
3        1
Name: LVI, dtype: int64


0

In [ ]:
print(df['PNI'].value_counts())
df['PNI']=df['PNI'].fillna(2)
df['PNI'].isna().sum()

2    2045
1     724
3     506
Name: PNI, dtype: int64


0

In [ ]:
print(df['pN'].value_counts())
df['pN']=df['pN'].fillna(2)
df['pN'].isna().sum()

2       1872
32       413
31       387
42       310
41       290
3         24
4         14
33         4
9999       3
Name: pN, dtype: int64


0

In [ ]:
print(df['Harvested_LN'].value_counts())
df['Harvested_LN']=df['Harvested_LN'].fillna(df['Harvested_LN'].mean())
df['Harvested_LN'].isna().sum()

12    210
14    163
13    161
20    151
15    151
     ... 
72      1
71      1
69      1
67      1
0       1
Name: Harvested_LN, Length: 97, dtype: int64


0

In [ ]:
print(df['Positive_LN'].value_counts())
df['Positive_LN']=df['Positive_LN'].fillna(df['Positive_LN'].mean())
df['Positive_LN'].isna().sum()

0       1840
1        395
2        250
3        166
4        122
5        103
6         67
7         60
8         41
9         34
10        24
11        20
12        19
14        17
15        12
13         8
19         7
24         7
18         7
22         7
17         6
16         5
9999       5
20         4
28         4
32         4
21         4
23         4
33         3
46         2
36         2
27         2
26         2
25         2
88         1
34         1
31         1
29         1
39         1
40         1
54         1
64         1
72         1
35         1
Name: Positive_LN, dtype: int64


0

In [ ]:
df.isna().sum()

Age                        0
Sex                        0
ASA                        0
BMI                        0
DM_history                 0
Pulmonary_disease          0
Liver_disease              0
Kidney_disease             0
Smoking_history            0
Prior_Dx_cancer            0
pT                         8
pM                         6
pTNM                       8
K-ras                      0
N-ras                      0
BRAF                       0
LVI                        0
PNI                        0
pN                         0
Harvested_LN               0
Positive_LN                0
Postop_Chemo_Regimen    1385
dtype: int64

In [ ]:
df

Age Sex ASA    BMI  ...  pN Harvested_LN Positive_LN Postop_Chemo_Regimen
2     73   2   3  16.25  ...  31         23.0         1.0                    1
3     63   1   2  23.88  ...  41         10.0         4.0                  NaN
4     45   2   2  21.83  ...   2         56.0         0.0                  NaN
5     69   1   3  22.86  ...  31         33.0         1.0                    1
6     69   1   2  20.81  ...  31         25.0         1.0                    1
...   ..  ..  ..    ...  ...  ..          ...         ...                  ...
3318  77   2   2  23.55  ...  32          6.0         3.0                    3
3319  77   2   2   21.7  ...   2         39.0         0.0                    3
3320  66   1   2  31.81  ...  42         15.0         7.0                3 + 7
3321  69   2   2  26.77  ...   2         16.0         0.0                  NaN
3322  61   1   3  23.71  ...  42         20.0        19.0                  NaN

[3321 rows x 22 columns]

In [ ]:
df['Postop_Chemo_Regimen']=df['Postop_Chemo_Regimen'].fillna(0)
df['Postop_Chemo_Regimen'].isna().sum()

0

In [ ]:
print(df['Postop_Chemo_Regimen'].value_counts())

0                   1385
3                    846
1                    593
2                    162
5 + 7                 66
4                     57
8                     53
5 + 6                 49
5                     43
3 + 7                 34
3 + 6                 13
8 (D-F cap)            7
2 + 8                  4
3+7                    3
8 (Helixor only)       1
7                      1
1 + 8(MMC)             1
5+7                    1
8 (Teroful)            1
8(UFT)                 1
Name: Postop_Chemo_Regimen, dtype: int64


In [ ]:
df = df[df['Postop_Chemo_Regimen'] != '5 + 7']
df = df[df['Postop_Chemo_Regimen'] != '5 + 6']
df = df[df['Postop_Chemo_Regimen'] != '8']
df = df[df['Postop_Chemo_Regimen'] != '3 + 7']
df = df[df['Postop_Chemo_Regimen'] != '3 + 6']
df = df[df['Postop_Chemo_Regimen'] != '8 (D-F cap)']
df = df[df['Postop_Chemo_Regimen'] != '2 + 8']
df = df[df['Postop_Chemo_Regimen'] != '3+7']
df = df[df['Postop_Chemo_Regimen'] != '1 + 8(MMC)']
df = df[df['Postop_Chemo_Regimen'] != '8 (Teroful)']
df = df[df['Postop_Chemo_Regimen'] != '8(UFT)']
df = df[df['Postop_Chemo_Regimen'] != '8 (Helixor only)']
df = df[df['Postop_Chemo_Regimen'] != 7]
df = df[df['Postop_Chemo_Regimen'] != 8]

df = df[df['Postop_Chemo_Regimen'] != '5+7']
df

Age Sex ASA    BMI  ...  pN Harvested_LN Positive_LN Postop_Chemo_Regimen
2     73   2   3  16.25  ...  31         23.0         1.0                    1
3     63   1   2  23.88  ...  41         10.0         4.0                    0
4     45   2   2  21.83  ...   2         56.0         0.0                    0
5     69   1   3  22.86  ...  31         33.0         1.0                    1
6     69   1   2  20.81  ...  31         25.0         1.0                    1
...   ..  ..  ..    ...  ...  ..          ...         ...                  ...
3317  75   1   2  18.52  ...  42         40.0        28.0                    0
3318  77   2   2  23.55  ...  32          6.0         3.0                    3
3319  77   2   2   21.7  ...   2         39.0         0.0                    3
3321  69   2   2  26.77  ...   2         16.0         0.0                    0
3322  61   1   3  23.71  ...  42         20.0        19.0                    0

[3086 rows x 22 columns]

In [ ]:
print(df['Postop_Chemo_Regimen'].value_counts())

0    1385
3     846
1     593
2     162
4      57
5      43
Name: Postop_Chemo_Regimen, dtype: int64


In [ ]:
print(df['pT'].value_counts())
df['pT']=df['pT'].fillna(6)
df['pT'].isna().sum()

6     1779
5      469
4      354
71     244
72     124
3       54
2       42
7       11
1        1
Name: pT, dtype: int64


0

In [ ]:
print(df['pM'].value_counts())
df['pM']=df['pM'].fillna(1)
df['pM'].isna().sum()

1     2807
21     204
22      52
2       15
42       1
23       1
Name: pM, dtype: int64


0

In [ ]:
print(df['pTNM'].value_counts())
df['pTNM']=df['pTNM'].fillna(21)
df['pTNM'].isna().sum()

21    861
1     681
32    646
33    293
4     167
31    115
0      91
22     79
41     71
42     39
23     31
2       2
43      1
3       1
Name: pTNM, dtype: int64


0

In [ ]:
df.isnull().sum()

Age                     0
Sex                     0
ASA                     0
BMI                     0
DM_history              0
Pulmonary_disease       0
Liver_disease           0
Kidney_disease          0
Smoking_history         0
Prior_Dx_cancer         0
pT                      0
pM                      0
pTNM                    0
K-ras                   0
N-ras                   0
BRAF                    0
LVI                     0
PNI                     0
pN                      0
Harvested_LN            0
Positive_LN             0
Postop_Chemo_Regimen    0
dtype: int64

In [ ]:
from scipy import stats
corr = stats.pointbiserialr(df['Age'], df['Postop_Chemo_Regimen'])
corr

PointbiserialrResult(correlation=-0.24952860726160803, pvalue=5.08189704914789e-45)

In [ ]:
corr = stats.pointbiserialr(df['BMI'], df['Postop_Chemo_Regimen'])
corr

PointbiserialrResult(correlation=0.012023915191846098, pvalue=0.5043229448947895)

In [ ]:
corr = stats.pointbiserialr(df['Harvested_LN'], df['Postop_Chemo_Regimen'])
corr

PointbiserialrResult(correlation=-0.005927263211354275, pvalue=0.7420502481140275)

In [ ]:
corr = stats.pointbiserialr(df['Positive_LN'], df['Postop_Chemo_Regimen'])
corr

PointbiserialrResult(correlation=-0.00949123487469133, pvalue=0.5981566223857933)

In [ ]:
from scipy.stats import chi2_contingency
chi = chi2_contingency(pd.crosstab(df['ASA'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 77.95861918626396, p-value: 8.69475632913345e-09


In [ ]:
chi = chi2_contingency(pd.crosstab(df['Sex'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 16.835237007373454, p-value: 0.0048231103592514795


In [ ]:
chi = chi2_contingency(pd.crosstab(df['DM_history'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 22.34348322729227, p-value: 0.00045044163155467525


In [ ]:
chi = chi2_contingency(pd.crosstab(df['Pulmonary_disease'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 13.511012916489411, p-value: 0.019032815410021556


In [ ]:
chi = chi2_contingency(pd.crosstab(df['Liver_disease'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 5.873778706885569, p-value: 0.31869522655634414


In [ ]:
chi = chi2_contingency(pd.crosstab(df['Kidney_disease'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 17.398021926838805, p-value: 0.06600779363906797


In [ ]:
chi = chi2_contingency(pd.crosstab(df['Smoking_history'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 236.7288948264025, p-value: 3.330023294853697e-45


In [ ]:
chi = chi2_contingency(pd.crosstab(df['Prior_Dx_cancer'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 231.13434126506115, p-value: 4.967103696902852e-44


In [ ]:
chi = chi2_contingency(pd.crosstab(df['pT'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 731.8940770234074, p-value: 5.177967322233318e-128


In [ ]:
chi = chi2_contingency(pd.crosstab(df['pM'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 812.4060555973874, p-value: 2.9176275572949e-155


In [ ]:
chi = chi2_contingency(pd.crosstab(df['pTNM'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 1901.7706005298114, p-value: 0.0


In [ ]:
chi = chi2_contingency(pd.crosstab(df['K-ras'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 247.81546560456712, p-value: 1.5626806013091122e-47


In [ ]:
chi = chi2_contingency(pd.crosstab(df['N-ras'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 112.42712430901472, p-value: 1.7272653313340734e-19


In [ ]:
chi = chi2_contingency(pd.crosstab(df['BRAF'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 90.7384344721815, p-value: 3.822548056130917e-15


In [ ]:
chi = chi2_contingency(pd.crosstab(df['LVI'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 582.499360463843, p-value: 1.411457147179848e-94


In [ ]:
chi = chi2_contingency(pd.crosstab(df['PNI'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 419.1558738673677, p-value: 7.851593724452786e-84


In [ ]:
chi = chi2_contingency(pd.crosstab(df['pN'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 858.0239594604764, p-value: 4.304402986582509e-154


In [ ]:
chi = chi2_contingency(pd.crosstab(df['BRAF'],df['Postop_Chemo_Regimen']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi[0], chi[1]))

Chi2 Statistic: 90.7384344721815, p-value: 3.822548056130917e-15


In [ ]:
target_col = 'Postop_Chemo_Regimen'
target = df[target_col]
# features = df[['Age', 'Sex', 'ASA', 'BMI', 'DM_history', 'Pulmonary_disease',
#         'Liver_disease', 'Kidney_disease', 'Smoking_history',
#         'Prior_Dx_cancer', 'Hereditary_colorectal_tumor',
#         'Perforation', 'Obstruction', 'Emergency',
#         'pT','pM', 'pTNM', 'K-ras', 'N-ras', 'BRAF']]
# features = df[['Age', 'Sex', 'ASA', 'BMI', 'DM_history', 'Pulmonary_disease',
#         'Liver_disease', 'Kidney_disease', 'Smoking_history',
#         'Prior_Dx_cancer','pT','pM', 'pTNM', 'K-ras', 'N-ras', 'BRAF', 'LVI', 'PNI', 'pN', 'Harvested_LN','Positive_LN']]

features = df[['Age', 'Sex', 'ASA', 'BMI', 'DM_history', 'Pulmonary_disease','Smoking_history',
        'Prior_Dx_cancer','pT','pM', 'pTNM', 'K-ras', 'N-ras', 'BRAF', 'LVI', 'PNI', 'pN', 'Harvested_LN','Positive_LN']]
target.value_counts()
features.value_counts()

Age  Sex  ASA   BMI    DM_history  Pulmonary_disease  Smoking_history  Prior_Dx_cancer  pT  pM  pTNM  K-ras  N-ras  BRAF  LVI  PNI  pN  Harvested_LN  Positive_LN
93   1    3     19.14  0           0                  0                2                5   1   1     1      1      1     32   2    2   15.000000     0.000000       1
58   1    2     22.37  0           0                  1                2                71  22  42    21     1      1     31   1    41  52.000000     4.000000       1
     2    9999  24.97  0           0                  0                2                4   1   1     22     21     21    32   2    2   16.000000     0.000000       1
                22.27  0           0                  1                2                6   1   32    21     1      1     31   1    32  14.000000     3.000000       1
          3     24.54  0           0                  0                2                5   1   1     22     21     21    32   2    2   6.000000      0.000000       1
   

In [ ]:
features.isnull().sum()

Age                  0
Sex                  0
ASA                  0
BMI                  0
DM_history           0
Pulmonary_disease    0
Smoking_history      0
Prior_Dx_cancer      0
pT                   0
pM                   0
pTNM                 0
K-ras                0
N-ras                0
BRAF                 0
LVI                  0
PNI                  0
pN                   0
Harvested_LN         0
Positive_LN          0
dtype: int64

In [ ]:
df

Age Sex ASA    BMI  ...  pN Harvested_LN Positive_LN Postop_Chemo_Regimen
2     73   2   3  16.25  ...  31         23.0         1.0                    1
3     63   1   2  23.88  ...  41         10.0         4.0                    0
4     45   2   2  21.83  ...   2         56.0         0.0                    0
5     69   1   3  22.86  ...  31         33.0         1.0                    1
6     69   1   2  20.81  ...  31         25.0         1.0                    1
...   ..  ..  ..    ...  ...  ..          ...         ...                  ...
3317  75   1   2  18.52  ...  42         40.0        28.0                    0
3318  77   2   2  23.55  ...  32          6.0         3.0                    3
3319  77   2   2   21.7  ...   2         39.0         0.0                    3
3321  69   2   2  26.77  ...   2         16.0         0.0                    0
3322  61   1   3  23.71  ...  42         20.0        19.0                    0

[3086 rows x 22 columns]

In [ ]:
features

Age Sex ASA    BMI DM_history  ... LVI PNI  pN  Harvested_LN  Positive_LN
2     73   2   3  16.25          0  ...  11   3  31          23.0          1.0
3     63   1   2  23.88          0  ...  32   3  41          10.0          4.0
4     45   2   2  21.83          0  ...  32   3   2          56.0          0.0
5     69   1   3  22.86          1  ...  32   3  31          33.0          1.0
6     69   1   2  20.81          0  ...  21   3  31          25.0          1.0
...   ..  ..  ..    ...        ...  ...  ..  ..  ..           ...          ...
3317  75   1   2  18.52          0  ...  31   2  42          40.0         28.0
3318  77   2   2  23.55          0  ...  31   1  32           6.0          3.0
3319  77   2   2   21.7          0  ...  31   1   2          39.0          0.0
3321  69   2   2  26.77          1  ...  31   1   2          16.0          0.0
3322  61   1   3  23.71          1  ...  31   1  42          20.0         19.0

[3086 rows x 19 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()
standardScaler.fit(df[['Age']])
df[['Age']] = standardScaler.transform(df[['Age']])
standardScaler.fit(df[['BMI']])
df[['BMI']] = standardScaler.transform(df[['BMI']])



In [ ]:
pd.get_dummies(df['pT'])
pd.get_dummies(df['BRAF'])
pd.get_dummies(df['N-ras'])
pd.get_dummies(df['K-ras'])
pd.get_dummies(df['pTNM'])
pd.get_dummies(df['pM'])
pd.get_dummies(df['Prior_Dx_cancer'])
pd.get_dummies(df['Smoking_history'])
pd.get_dummies(df['ASA'])


1     2     3     4     9999
2        0     0     1     0     0
3        0     1     0     0     0
4        0     1     0     0     0
5        0     0     1     0     0
6        0     1     0     0     0
...    ...   ...   ...   ...   ...
3317     0     1     0     0     0
3318     0     1     0     0     0
3319     0     1     0     0     0
3321     0     1     0     0     0
3322     0     0     1     0     0

[3086 rows x 5 columns]

In [ ]:
import scipy.stats as stats

corr = stats.spearmanr(df['Age'], df['Postop_Chemo_Regimen'])
corr

SpearmanrResult(correlation=-0.26901470727909815, pvalue=2.6211401495273534e-52)

In [ ]:
import matplotlib.pyplot as plt 
import seaborn as sns

df_1 = df[['Age', 'BMI', 'Harvested_LN', 'Positive_LN']]
corr1 = stats.spearmanr(df_1['Harvested_LN'], df_1['BMI'])
corr1

SpearmanrResult(correlation=-0.14730207337958393, pvalue=1.960440139418787e-16)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    features, target, test_size = 0.3, random_state=3
)

In [ ]:
#kNN


from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
knn = KNeighborsClassifier()
y_train = y_train.astype('int')
y_test=y_test.astype('int')

knn.fit(X_train, y_train)
print("테스트 세트 정확도 : {:.2f}".format(knn.score(X_test, y_test)))

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report

y_pred = knn.predict(X_test)

print(classification_report(y_test,y_pred))

print(precision_score(y_test, y_pred,average='macro'))
print(recall_score(y_test, y_pred,average='macro'))
print(f1_score(y_test, y_pred,average='macro'))
print(accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

테스트 세트 정확도 : 0.61
              precision    recall  f1-score   support

           0       0.70      0.82      0.75       424
           1       0.46      0.47      0.47       167
           2       0.17      0.04      0.06        57
           3       0.58      0.56      0.57       250
           4       0.00      0.00      0.00        14
           5       0.29      0.14      0.19        14

    accuracy                           0.61       926
   macro avg       0.37      0.34      0.34       926
weighted avg       0.57      0.61      0.59       926

0.3659419024008035
0.33696090789999894
0.3394481404656804
0.6144708423326134
[[348  33   1  40   0   2]
 [ 57  78   2  30   0   0]
 [ 33   9   2  13   0   0]
 [ 54  46   7 139   1   3]
 [  1   2   0  11   0   0]
 [  6   0   0   6   0   2]]


In [ ]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import cross_validate

In [ ]:
X = features
y = target.astype(int)
names = ["KNN", "SVM_Linear", "SVM_rbf", "DecisionTree", "RandomForest"]
scoring = {'acc': 'accuracy',
           'prec_macro': 'precision_macro',
           'rec_macro': 'recall_macro',
           'f1_macro' : 'f1_macro'}
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold(n_splits=5, random_state=0, shuffle=True)
accuracy_scores = []
precision_scores = []
recall_scores = []
f1_scores = []
for i, (train, test) in enumerate(cv.split(X, y)):
    print("=================", str(i) , " Fold =================")
    X_train = X.iloc[train]
    X_test = X.iloc[test]
    y_train = y.iloc[train]
    y_test = y.iloc[test]
    model = knn
    model.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    #print(classification_report(y_test,y_pred))
    print("accuracy_score : ", accuracy_score(y_test, y_pred))
    print("precision_macro : ", precision_score(y_test, y_pred,average='macro'))
    print("recall_macro : ",recall_score(y_test, y_pred,average='macro'))
    print("f1_macro : ",f1_score(y_test, y_pred,average='macro'))
    accuracy_scores.append(accuracy_score(y_test, y_pred))
    precision_scores.append(precision_score(y_test, y_pred,average='macro'))
    recall_scores.append(recall_score(y_test, y_pred,average='macro'))
    f1_scores.append(f1_score(y_test, y_pred,average='macro'))
print("")
print("Acc 평균 : ", np.mean(accuracy_scores))
print("prec 평균 : ", np.mean(precision_scores))
print("Recall 평균 : ", np.mean(recall_scores))
print("F1 평균 : ", np.mean(f1_scores))

================= 0  Fold =================
accuracy_score :  0.5906148867313916
precision_macro :  0.37742228835978836
recall_macro :  0.33774391074038235
f1_macro :  0.3458021848451793
================= 1  Fold =================
accuracy_score :  0.6094003241491086
precision_macro :  0.4767750620236549
recall_macro :  0.3266103144512124
f1_macro :  0.3380459106420645
================= 2  Fold =================
accuracy_score :  0.6175040518638574
precision_macro :  0.3627375094267977
recall_macro :  0.3339677657948114
f1_macro :  0.3347697337263007
================= 3  Fold =================
accuracy_score :  0.5980551053484603
precision_macro :  0.34194565223241363
recall_macro :  0.33367108195403095
f1_macro :  0.33368360999287644
================= 4  Fold =================
accuracy_score :  0.593192868719611
precision_macro :  0.4037756063228009
recall_macro :  0.38706466197182055
f1_macro :  0.38962043962699816

Acc 평균 :  0.6017534473624858
prec 평균 :  0.39253122367309107
Recall 평

In [ ]:
# #SVM_Linear
# from sklearn import svm
# svm_linear = svm.SVC(kernel='linear',random_state = 0)
# svm_linear.fit(X_train, y_train)
# print(svm_linear.score(X_test, y_test))

# from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report

# y_pred = svm_linear.predict(X_test)

# print(classification_report(y_test,y_pred))
# print(precision_score(y_test, y_pred,average='macro'))
# print(recall_score(y_test, y_pred,average='macro'))
# print(f1_score(y_test, y_pred,average='macro'))
# print(accuracy_score(y_test, y_pred))

# from sklearn.metrics import confusion_matrix
# print(confusion_matrix(y_test, y_pred))

In [ ]:
# X = features
# y = target.astype(int)
# names = ["KNN", "SVM_Linear", "SVM_rbf", "DecisionTree", "RandomForest"]
# scoring = {'acc': 'accuracy',
#            'prec_macro': 'precision_macro',
#            'rec_macro': 'recall_macro',
#            'f1_macro' : 'f1_macro'}
# from sklearn.model_selection import StratifiedKFold
# cv = StratifiedKFold(n_splits=5, random_state=0, shuffle=True)
# accuracy_scores = []
# precision_scores = []
# recall_scores = []
# f1_scores = []
# for i, (train, test) in enumerate(cv.split(X, y)):
#     print("=================", str(i) , " Fold =================")
#     X_train = X.iloc[train]
#     X_test = X.iloc[test]
#     y_train = y.iloc[train]
#     y_test = y.iloc[test]
#     model = svm_linear
#     model.fit(X_train, y_train)
#     y_pred = svm_linear.predict(X_test)
#     #print(classification_report(y_test,y_pred))
#     print("accuracy_score : ", accuracy_score(y_test, y_pred))
#     print("precision_macro : ", precision_score(y_test, y_pred,average='macro'))
#     print("recall_macro : ",recall_score(y_test, y_pred,average='macro'))
#     print("f1_macro : ",f1_score(y_test, y_pred,average='macro'))
#     accuracy_scores.append(accuracy_score(y_test, y_pred))
#     precision_scores.append(precision_score(y_test, y_pred,average='macro'))
#     recall_scores.append(recall_score(y_test, y_pred,average='macro'))
#     f1_scores.append(f1_score(y_test, y_pred,average='macro'))
# print("")
# print("Acc 평균 : ", np.mean(accuracy_scores))
# print("prec 평균 : ", np.mean(precision_scores))
# print("Recall 평균 : ", np.mean(recall_scores))
# print("F1 평균 : ", np.mean(f1_scores))

In [ ]:
# #SVM_rbf
# from sklearn import svm
# svm_rbf = svm.SVC(kernel='rbf',random_state = 0)
# svm_rbf.fit(X_train, y_train)
# print(svm_rbf.score(X_test, y_test))


In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
DTree = DecisionTreeClassifier(random_state = 0)
DTree.fit(X_train, y_train)
print(DTree.score(X_test, y_test))

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report

y_pred = DTree.predict(X_test)

print(classification_report(y_test,y_pred))

print(precision_score(y_test, y_pred,average='macro'))
print(recall_score(y_test, y_pred,average='macro'))
print(f1_score(y_test, y_pred,average='macro'))
print(accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

0.5996758508914101
              precision    recall  f1-score   support

           0       0.73      0.71      0.72       277
           1       0.48      0.50      0.49       118
           2       0.03      0.03      0.03        33
           3       0.62      0.65      0.64       169
           4       0.10      0.08      0.09        12
           5       0.30      0.38      0.33         8

    accuracy                           0.60       617
   macro avg       0.38      0.39      0.38       617
weighted avg       0.60      0.60      0.60       617

0.3780304629778994
0.39118419417294725
0.38365900394382585
0.5996758508914101
[[196  38  14  24   3   2]
 [ 32  59   7  19   1   0]
 [ 14   5   1  13   0   0]
 [ 22  20   7 110   5   5]
 [  4   0   0   7   1   0]
 [  1   0   0   4   0   3]]


In [ ]:
X = features
y = target.astype(int)
names = ["KNN", "SVM_Linear", "SVM_rbf", "DecisionTree", "RandomForest"]
scoring = {'acc': 'accuracy',
           'prec_macro': 'precision_macro',
           'rec_macro': 'recall_macro',
           'f1_macro' : 'f1_macro'}
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold(n_splits=5, random_state=0, shuffle=True)
accuracy_scores = []
precision_scores = []
recall_scores = []
f1_scores = []
for i, (train, test) in enumerate(cv.split(X, y)):
    print("=================", str(i) , " Fold =================")
    X_train = X.iloc[train]
    X_test = X.iloc[test]
    y_train = y.iloc[train]
    y_test = y.iloc[test]
    model = DTree
    model.fit(X_train, y_train)
    y_pred = DTree.predict(X_test)
    #print(classification_report(y_test,y_pred))
    print("accuracy_score : ", accuracy_score(y_test, y_pred))
    print("precision_macro : ", precision_score(y_test, y_pred,average='macro'))
    print("recall_macro : ",recall_score(y_test, y_pred,average='macro'))
    print("f1_macro : ",f1_score(y_test, y_pred,average='macro'))
    accuracy_scores.append(accuracy_score(y_test, y_pred))
    precision_scores.append(precision_score(y_test, y_pred,average='macro'))
    recall_scores.append(recall_score(y_test, y_pred,average='macro'))
    f1_scores.append(f1_score(y_test, y_pred,average='macro'))
print("")
print("Acc 평균 : ", np.mean(accuracy_scores))
print("prec 평균 : ", np.mean(precision_scores))
print("Recall 평균 : ", np.mean(recall_scores))
print("F1 평균 : ", np.mean(f1_scores))

================= 0  Fold =================
accuracy_score :  0.5307443365695793
precision_macro :  0.30772032593199056
recall_macro :  0.30142614986387956
f1_macro :  0.30384653861544614
================= 1  Fold =================
accuracy_score :  0.5364667747163695
precision_macro :  0.31286265047016254
recall_macro :  0.31241738507387756
f1_macro :  0.31218703713890467
================= 2  Fold =================
accuracy_score :  0.5737439222042139
precision_macro :  0.425858905554791
recall_macro :  0.36103330480683793
f1_macro :  0.37990018866130976
================= 3  Fold =================
accuracy_score :  0.580226904376013
precision_macro :  0.34644956697095736
recall_macro :  0.35405185158190355
f1_macro :  0.34898909176397647
================= 4  Fold =================
accuracy_score :  0.5996758508914101
precision_macro :  0.3780304629778994
recall_macro :  0.39118419417294725
f1_macro :  0.38365900394382585

Acc 평균 :  0.5641715577515172
prec 평균 :  0.3541843823811602
Reca

In [ ]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=10)
RF.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report

y_pred = RF.predict(X_test)

print(precision_score(y_test, y_pred,average='macro'))
print(recall_score(y_test, y_pred,average='macro'))
print(f1_score(y_test, y_pred,average='macro'))
print(accuracy_score(y_test, y_pred))


from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

0.49865388401657834
0.4148079143716537
0.43199822264507154
0.6823338735818476
[[229  23   2  23   0   0]
 [ 31  66   1  20   0   0]
 [ 15   3   0  15   0   0]
 [ 28  16   2 123   0   0]
 [  3   0   0   9   0   0]
 [  2   0   0   3   0   3]]


In [ ]:
X = features
y = target.astype(int)
names = ["KNN", "SVM_Linear", "SVM_rbf", "DecisionTree", "RandomForest"]
scoring = {'acc': 'accuracy',
           'prec_macro': 'precision_macro',
           'rec_macro': 'recall_macro',
           'f1_macro' : 'f1_macro'}
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold(n_splits=5, random_state=0, shuffle=True)
accuracy_scores = []
precision_scores = []
recall_scores = []
f1_scores = []
for i, (train, test) in enumerate(cv.split(X, y)):
    print("=================", str(i) , " Fold =================")
    X_train = X.iloc[train]
    X_test = X.iloc[test]
    y_train = y.iloc[train]
    y_test = y.iloc[test]
    model = RF
    model.fit(X_train, y_train)
    y_pred = RF.predict(X_test)
    #print(classification_report(y_test,y_pred))
    print("accuracy_score : ", accuracy_score(y_test, y_pred))
    print("precision_macro : ", precision_score(y_test, y_pred,average='macro'))
    print("recall_macro : ",recall_score(y_test, y_pred,average='macro'))
    print("f1_macro : ",f1_score(y_test, y_pred,average='macro'))
    accuracy_scores.append(accuracy_score(y_test, y_pred))
    precision_scores.append(precision_score(y_test, y_pred,average='macro'))
    recall_scores.append(recall_score(y_test, y_pred,average='macro'))
    f1_scores.append(f1_score(y_test, y_pred,average='macro'))
print("")
print("Acc 평균 : ", np.mean(accuracy_scores))
print("prec 평균 : ", np.mean(precision_scores))
print("Recall 평균 : ", np.mean(recall_scores))
print("F1 평균 : ", np.mean(f1_scores))

================= 0  Fold =================
accuracy_score :  0.627831715210356
precision_macro :  0.397318624503914
recall_macro :  0.3716547985695036
f1_macro :  0.37842891171150644
================= 1  Fold =================
accuracy_score :  0.6239870340356564
precision_macro :  0.3271173675207326
recall_macro :  0.31488511456213447
f1_macro :  0.3084295775634857
================= 2  Fold =================
accuracy_score :  0.6677471636952999
precision_macro :  0.42634296002351557
recall_macro :  0.35921635453883444
f1_macro :  0.3676775997370026
================= 3  Fold =================
accuracy_score :  0.6418152350081038
precision_macro :  0.4075233004099759
recall_macro :  0.35853917556062925
f1_macro :  0.36775450983720637
================= 4  Fold =================
accuracy_score :  0.6580226904376013
precision_macro :  0.35474970696276015
recall_macro :  0.34873636188713447
f1_macro :  0.3435610711229675

Acc 평균 :  0.6438807676774034
prec 평균 :  0.3826103918841796
Recall 평균

In [ ]:
print(recall_score(y_test, y_pred, average='weighted'))


0.6580226904376013


In [ ]:
from lightgbm import LGBMClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV

lgbm_wrapper = LGBMClassifier(n_estimators=400)


In [ ]:
'''
# df['pT']= pd.to_numeric(df['pT'])
# df['BRAF']= pd.to_numeric(df['BRAF'])
# df['N-ras']= pd.to_numeric(df['N-ras'])
# df['K-ras']= pd.to_numeric(df['K-ras'])
# df['pTNM']= pd.to_numeric(df['pTNM'])
# df['pM']= pd.to_numeric(df['pM'])
# df['Prior_Dx_cancer']= pd.to_numeric(df['Prior_Dx_cancer'])
# df['ASA']= pd.to_numeric(df['ASA'])
df['Age']= pd.to_numeric(df['Age'])
df['Harvested_LN']= pd.to_numeric(df['Harvested_LN'])
df['Positive_LN']= pd.to_numeric(df['Positive_LN'])

# df['Sex']= pd.to_numeric(df['Sex'])
df['BMI']= pd.to_numeric(df['BMI'])
# df['Pulmonary_disease']= pd.to_numeric(df['Pulmonary_disease'])
# df['Liver_disease']= pd.to_numeric(df['Liver_disease'])
# df['Kidney_disease']= pd.to_numeric(df['Kidney_disease'])
'''

"\n# df['pT']= pd.to_numeric(df['pT'])\n# df['BRAF']= pd.to_numeric(df['BRAF'])\n# df['N-ras']= pd.to_numeric(df['N-ras'])\n# df['K-ras']= pd.to_numeric(df['K-ras'])\n# df['pTNM']= pd.to_numeric(df['pTNM'])\n# df['pM']= pd.to_numeric(df['pM'])\n# df['Prior_Dx_cancer']= pd.to_numeric(df['Prior_Dx_cancer'])\n# df['ASA']= pd.to_numeric(df['ASA'])\ndf['Age']= pd.to_numeric(df['Age'])\ndf['Harvested_LN']= pd.to_numeric(df['Harvested_LN'])\ndf['Positive_LN']= pd.to_numeric(df['Positive_LN'])\n\n# df['Sex']= pd.to_numeric(df['Sex'])\ndf['BMI']= pd.to_numeric(df['BMI'])\n# df['Pulmonary_disease']= pd.to_numeric(df['Pulmonary_disease'])\n# df['Liver_disease']= pd.to_numeric(df['Liver_disease'])\n# df['Kidney_disease']= pd.to_numeric(df['Kidney_disease'])\n"

In [ ]:
# pd.get_dummies(df, columns = ['Sex', 'ASA', 'Pulmonary_disease','Liver_disease', 'Kidney_disease', 'Prior_Dx_cancer', 'pT', 'pM', 'pTNM', 'K-ras', 'N-ras', 'BRAF', 'LVI', 'PNI','pN'], drop_first = True)

In [ ]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(
#     features, target, random_state=0
# )

In [ ]:
# list(df.columns.values)

In [ ]:
'''
# https://somjang.tistory.com/entry/LGBMClassifier-ValueError-DataFramedtypes-for-data-must-be-int-float-or-bool-Did-not-expect-the-data-types-in-the-following-fields-%ED%95%B4%EA%B2%B0%EB%B0%A9%EB%B2%95
target_col = 'Postop_Chemo_Regimen'
target = df[target_col]
# features = df[['Age', 'Sex', 'ASA', 'BMI', 'DM_history', 'Pulmonary_disease',
#         'Liver_disease', 'Kidney_disease', 'Smoking_history',
#         'Prior_Dx_cancer', 'Hereditary_colorectal_tumor',
#         'Perforation', 'Obstruction', 'Emergency',
#         'pT','pM', 'pTNM', 'K-ras', 'N-ras', 'BRAF']]



features = df[['Age',
 'Sex',
 'ASA',
 'BMI',
 'Pulmonary_disease',
#  'Liver_disease',
#  'Kidney_disease',
 'Smoking_history',
 'Prior_Dx_cancer',
 'pT',
 'pM',
 'pTNM',
 'K-ras',
 'N-ras',
 'BRAF',
 'LVI',
 'PNI',
 'pN',
 'Harvested_LN',
 'Positive_LN']]
features = features.astype(int)
target.value_counts()
features.value_counts()
'''


"\n# https://somjang.tistory.com/entry/LGBMClassifier-ValueError-DataFramedtypes-for-data-must-be-int-float-or-bool-Did-not-expect-the-data-types-in-the-following-fields-%ED%95%B4%EA%B2%B0%EB%B0%A9%EB%B2%95\ntarget_col = 'Postop_Chemo_Regimen'\ntarget = df[target_col]\n# features = df[['Age', 'Sex', 'ASA', 'BMI', 'DM_history', 'Pulmonary_disease',\n#         'Liver_disease', 'Kidney_disease', 'Smoking_history',\n#         'Prior_Dx_cancer', 'Hereditary_colorectal_tumor',\n#         'Perforation', 'Obstruction', 'Emergency',\n#         'pT','pM', 'pTNM', 'K-ras', 'N-ras', 'BRAF']]\n\n\n\nfeatures = df[['Age',\n 'Sex',\n 'ASA',\n 'BMI',\n 'Pulmonary_disease',\n#  'Liver_disease',\n#  'Kidney_disease',\n 'Smoking_history',\n 'Prior_Dx_cancer',\n 'pT',\n 'pM',\n 'pTNM',\n 'K-ras',\n 'N-ras',\n 'BRAF',\n 'LVI',\n 'PNI',\n 'pN',\n 'Harvested_LN',\n 'Positive_LN']]\nfeatures = features.astype(int)\ntarget.value_counts()\nfeatures.value_counts()\n"

In [ ]:
features.isnull().sum()

Age                  0
Sex                  0
ASA                  0
BMI                  0
DM_history           0
Pulmonary_disease    0
Smoking_history      0
Prior_Dx_cancer      0
pT                   0
pM                   0
pTNM                 0
K-ras                0
N-ras                0
BRAF                 0
LVI                  0
PNI                  0
pN                   0
Harvested_LN         0
Positive_LN          0
dtype: int64

In [ ]:
#LGBM
import lightgbm as lgb
from sklearn.preprocessing import LabelEncoder


for col in X_train.columns:
  X_train[col] = X_train[col].astype(int)
y_train = y_train.astype(int)

for col in X_test.columns:
  X_test[col] = X_test[col].astype(int)
y_test = y_test.astype(int)

lgbm_wrapper = LGBMClassifier(max_depth=100,
                              objective='multiclass',
                              # tweedie_variance_power = 1.1,
                              # sub_row=0.75,
                              # lambda_l2 = 0.1,
                              boosting_type='goss',
                              learning_rate=0.014,
                              early_stopping_rounds=100,
                              max_leaves = 100,
                              min_data_in_leaf = 2,
                              n_estimators = 200,
                              # bagging_fraction = 0.6,
                              # feature_fraction = 0.7,
                              # bagging_freq = 1,
                              # bagging_seed = 2018,
                              # random_state = 95,
                              )



# lgbm_params = {'max_depth' : [300, 600, 1000],
#                'objective' : ['multiclass'],
#                'learning_rate' : [0.014, 0.07, 0.009],
#                'num_iterations' : [100, 500, 1000],
#                'boosting_type' : ['dart', 'goss'],
#                'early_stopping_round' : [300],
#                'n_estimators':[100, 500],
#                'num_leaves' :[500],}
# lgbm_wrapper = LGBMClassifier()
# lgbm_go = GridSearchCV(lgbm_wrapper, param_grid = lgbm_params, cv=3, refit=True)
# evals = [(X_test, y_test)]
# lgbm_go.fit(X_train, y_train, eval_metric='multi_logloss',
#             eval_set=[(X_test, y_test)], 
#             verbose=500)


lgbm_wrapper.fit(X_train, y_train,
                 eval_metric='multi_logloss',
                 eval_set=[(X_test, y_test)],
                 verbose=300)


Training until validation scores don't improve for 100 rounds.
Did not meet early stopping. Best iteration is:
[200]	valid_0's multi_logloss: 0.919233	valid_0's multi_logloss: 0.919233


LGBMClassifier(boosting_type='goss', class_weight=None, colsample_bytree=1.0,
               early_stopping_rounds=100, importance_type='split',
               learning_rate=0.014, max_depth=100, max_leaves=100,
               min_child_samples=20, min_child_weight=0.001, min_data_in_leaf=2,
               min_split_gain=0.0, n_estimators=200, n_jobs=-1, num_leaves=31,
               objective='multiclass', random_state=None, reg_alpha=0.0,
               reg_lambda=0.0, silent=True, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)

In [ ]:
y_train.shape

(2469,)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

def top_n_accuracy(X_train, y_train, X_test,y_test,n,classifier):
  # X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
  vectorizer = TfidfVectorizer(min_df=2)
  X_train_sparse = vectorizer.fit_transform(X_train)
  feature_names = vectorizer.get_feature_names()
  test = vectorizer.transform(X_test)
  clf = classifier
  clf.fit(X_train.values.reshape(-1, 1), y_train,
                 eval_metric='multi_logloss',
                 eval_set=[(X_test, y_test)],
                 verbose=300)
  # clf.fit(X_train,y_train)
  predictions = clf.predict(test)
  probs = clf.predict_proba(test)
  topn = np.argsort(probs, axis = 1)[:,-n:]
  y_true = np.array(y_test)

  return np.mean(np.array([1 if y_true[k] in topn[k] else 0 for k in range(len(topn))]))

top2 = top_n_accuracy(X_train, y_train, X_test, y_test, 2, lgbm_wrapper)

ValueError: ignored

In [ ]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report

# y_pred = lgbm_wrapper.predict(X_test)
y_pred = lgbm_go.predict(X_test)

print(classification_report(y_test,y_pred))

print(precision_score(y_test, y_pred,average='macro'))
print(recall_score(y_test, y_pred,average='macro'))
print(f1_score(y_test, y_pred,average='macro'))
print(accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

In [ ]:
X = features
y = target.astype(int)
names = ["KNN", "SVM_Linear", "SVM_rbf", "DecisionTree", "RandomForest"]
scoring = {'acc': 'accuracy',
           'prec_macro': 'precision_macro',
           'rec_macro': 'recall_macro',
           'f1_macro' : 'f1_macro'}
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold(n_splits=5, random_state=0, shuffle=True)
accuracy_scores = []
precision_scores = []
recall_scores = []
f1_scores = []
for i, (train, test) in enumerate(cv.split(X, y)):
    print("=================", str(i) , " Fold =================")
    X_train = X.iloc[train]
    X_test = X.iloc[test]
    y_train = y.iloc[train]
    y_test = y.iloc[test]
    for col in X_train.columns:
      X_train[col] = X_train[col].astype(int)
      y_train = y_train.astype(int)
    for col in X_test.columns:
      X_test[col] = X_test[col].astype(int)
      y_test = y_test.astype(int)
    model = lgbm_wrapper
    model.fit(X_train, y_train,
                 eval_metric='multiclass',
                 eval_set=[(X_test, y_test)],
                 verbose=250,)
    y_pred = lgbm_wrapper.predict(X_test)
    #print(classification_report(y_test,y_pred))
    print("accuracy_score : ", accuracy_score(y_test, y_pred))
    print("precision_macro : ", precision_score(y_test, y_pred,average='macro'))
    print("recall_macro : ",recall_score(y_test, y_pred,average='macro'))
    print("f1_macro : ",f1_score(y_test, y_pred,average='macro'))
    accuracy_scores.append(accuracy_score(y_test, y_pred))
    precision_scores.append(precision_score(y_test, y_pred,average='macro'))
    recall_scores.append(recall_score(y_test, y_pred,average='macro'))
    f1_scores.append(f1_score(y_test, y_pred,average='macro'))
print("")
print("Acc 평균 : ", np.mean(accuracy_scores))
print("prec 평균 : ", np.mean(precision_scores))
print("Recall 평균 : ", np.mean(recall_scores))
print("F1 평균 : ", np.mean(f1_scores))

In [ ]:
import matplotlib.pyplot as plt

lgbm_result = lgbm_wrapper.fit(X_train, y_train,
                 eval_metric='multiclass',
                 eval_set=[(X_test, y_test),(X_train, y_train)],
                 verbose=100)
print(classification_report(y_test,y_pred))


lgb.plot_metric(lgbm_result,xlim=(0,200))
 

In [ ]:
from matplotlib import pyplot as plt
from lightgbm import plot_importance
fig, ax = plt.subplots(figsize=(10,8))
plot_importance(lgbm_wrapper, ax = ax)